dist: trusty
sudo: required
serviced:
  - docker
addons:
  apt:
    update: true
    sources:
      - git-core
    packages:
      - git
      - docker-ce
language: node_js
node_js:
  - '9'
install: npm install
script:
  - bash ./deploy/deploy.sh
