dist: trusty
sudo: required
serviced:
  - docker
addons:
  apt:
    update: true
    sources:
      - git-core
    packages:
      - git
language: node_js
node_js:
  - '10'
before_install:
  - sudo apt-get update -y -qq docker-ce
install: npm install
script:
  - bash ./deploy/deploy.sh
