dist: trusty
sudo: required
addons:
  apt:
    update: true
    sources:
      - git-core
    packages:
      - git
language: node_js
node_js:
  - '10'
install: npm install
cache:
  directories:
    - "node_modules"
script:
  - bash ./deploy/test.sh
