dist: trusty
sudo: required
serviced:
  - docker
addons:
  apt:
    update: true
    sources:
      - git-core
    packages:
      - git
language: node_js
node_js:
  - '10'
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/pubkeys.gpg
  - echo "dep http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - suo apt-get update -qq
  - sudo apt-get update -y -qq docker-ce
  - curl -o- -L https://yarnpkg.com/install.sh | bash
cache:
  yarn: true
install: npm install
script:
  - bash ./deploy/deploy.sh
