module.exports = {
    BotToken: "",
    YoutubeAPIKey: "",
    OwnerID: "",
    TwitchClientID: "",
    riotAPI: "",
    standardCommandPermissions: {
        disable: false,
        enable: false,
        groups: false,
        load: false,
        reload: false,
        unload: false,

        eval: false,
        help: true,
        ping: true,
        prefix: false,

        addrole: false,
        ban: false,
        invite: true,
        joinrole: true,
        leaverole: true,
        permission: false,
        removerole: false,
        twitch: true,
        userinfo: true,

        addlyrics: true,
        join: true,
        leave: true,
        loop: true,
        lyrics: true,
        pause: true,
        play: true,
        queueremove: true,
        queue: true,
        queueadd: true,
        record: false,
        removelyrics: false,
        resetmusicchannel: true,
        resume: true,
        search: true,
        setmusicchannel: true,
        setvolume: true,
        shuffle: true,
        skip: true,
        songinfo: true,

        give: true,
        points: true
    }
}